/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rpl;

import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shinchank
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    private modelRPL model;

    public Gui() {
        model = new modelRPL();
        initComponents();
        DefaultListCellRenderer renderer = (DefaultListCellRenderer) ListPenghuni.getCellRenderer();//Alignment Center  
        renderer.setHorizontalAlignment(SwingConstants.LEFT); //Alignment Left Jlist
        ScrollPane.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0)); //Hide Scrollbar JScrollPanel
        DefaultTableCellRenderer renderer1 = (DefaultTableCellRenderer) TabelPenghuni.getCellRenderer(0, 0);
        renderer.setHorizontalAlignment(SwingConstants.LEFT); //Alignment Left Jlist
        ScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0)); //Hide Scrollbar JScrollPanel
        PesanArea.setLineWrap(true);
        ScrollPesan.getVerticalScrollBar().setPreferredSize(new Dimension(0, 0));
        setView(true, false, false, false, false, false, false, false, false, false);
    }

    public void setView(boolean login, boolean halamanUtama, boolean kData, boolean kPembayaran, boolean iData, boolean hData, boolean cData, boolean kirim, boolean bayar, boolean status) {
        //isinya panel semua
        PanelLogin.setVisible(login);
        PanelHalamanUtama.setVisible(halamanUtama);
        PanelKelolaDataPenghuni.setVisible(kData);
        PanelKelolaPembayaran.setVisible(kPembayaran);
        PanelInputDataPenghuni.setVisible(iData);
        PanelHapusDataPenghuni.setVisible(hData);
        PanelCekDataPenghuni.setVisible(cData);
        PanelKirimPesan.setVisible(kirim);
        PanelKonfirmasiPembayaran.setVisible(bayar);
        PanelStatusTransaksi.setVisible(status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Move = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btnMasuk = new javax.swing.JLabel();
        LabelSalahLogin = new javax.swing.JLabel();
        BG3 = new javax.swing.JLabel();
        PanelStatusTransaksi = new javax.swing.JPanel();
        btnBack6 = new javax.swing.JLabel();
        BG10 = new javax.swing.JLabel();
        PanelKonfirmasiPembayaran = new javax.swing.JPanel();
        btnKonfirmasi = new javax.swing.JLabel();
        btnBack5 = new javax.swing.JLabel();
        BG9 = new javax.swing.JLabel();
        PanelHapusDataPenghuni = new javax.swing.JPanel();
        ScrollPane = new javax.swing.JScrollPane();
        ListPenghuni = new javax.swing.JList();
        btnHapus = new javax.swing.JLabel();
        LabelInfoHapus = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JLabel();
        BG5 = new javax.swing.JLabel();
        PanelCekDataPenghuni = new javax.swing.JPanel();
        ScrollPane1 = new javax.swing.JScrollPane();
        TabelPenghuni = new javax.swing.JTable();
        btnBack3 = new javax.swing.JLabel();
        BG6 = new javax.swing.JLabel();
        PanelKelolaDataPenghuni = new javax.swing.JPanel();
        btnInputDataPenghuni = new javax.swing.JLabel();
        btnHapusDataPenghuni = new javax.swing.JLabel();
        btnCekDataPenghuni = new javax.swing.JLabel();
        btnKembali = new javax.swing.JLabel();
        BG2 = new javax.swing.JLabel();
        PanelKelolaPembayaran = new javax.swing.JPanel();
        btnStatusPembayaran = new javax.swing.JLabel();
        btnKonfirmasiPembayaran = new javax.swing.JLabel();
        btnKembaliPembayaran = new javax.swing.JLabel();
        BG7 = new javax.swing.JLabel();
        PanelKirimPesan = new javax.swing.JPanel();
        btnKirim = new javax.swing.JLabel();
        ScrollPesan = new javax.swing.JScrollPane();
        PesanArea = new javax.swing.JTextArea();
        btnBack4 = new javax.swing.JLabel();
        BG8 = new javax.swing.JLabel();
        PanelHalamanUtama = new javax.swing.JPanel();
        btnKelolaDataHU = new javax.swing.JLabel();
        btnKelolaPembarayan = new javax.swing.JLabel();
        btnKirimPesan = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();
        PanelInputDataPenghuni = new javax.swing.JPanel();
        tfNamaPenghuni = new javax.swing.JTextField();
        tfNoKamar = new javax.swing.JTextField();
        tfNoHP = new javax.swing.JTextField();
        tfAsalPenghuni = new javax.swing.JTextField();
        btnInput = new javax.swing.JLabel();
        LabelSalahInputData = new javax.swing.JLabel();
        BG4 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 480));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MoveMouseDragged(evt);
            }
        });
        Move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MoveMousePressed(evt);
            }
        });
        getContentPane().add(Move, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 20));

        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfUsername.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUsername.setText("Nama Pengguna");
        tfUsername.setToolTipText("Nama Pengguna");
        tfUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelLogin.add(tfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 244, 270, 35));

        tfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelLogin.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 311, 270, 35));

        btnMasuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMasukMouseReleased(evt);
            }
        });
        PanelLogin.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 393, 120, 50));

        LabelSalahLogin.setForeground(new java.awt.Color(212, 14, 14));
        LabelSalahLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelLogin.add(LabelSalahLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 355, 290, 20));

        BG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xlog in.JPG"))); // NOI18N
        PanelLogin.add(BG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelStatusTransaksi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBack6MouseReleased(evt);
            }
        });
        PanelStatusTransaksi.add(btnBack6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 20, 20));

        BG10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xstatus transaksi.JPG"))); // NOI18N
        PanelStatusTransaksi.add(BG10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelStatusTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelKonfirmasiPembayaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKonfirmasi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKonfirmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKonfirmasiMouseReleased(evt);
            }
        });
        PanelKonfirmasiPembayaran.add(btnKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 360, 103, 50));

        btnBack5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBack5MouseReleased(evt);
            }
        });
        PanelKonfirmasiPembayaran.add(btnBack5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 20, 20));

        BG9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xkonfirmasi pembayaran.JPG"))); // NOI18N
        PanelKonfirmasiPembayaran.add(BG9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelKonfirmasiPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelHapusDataPenghuni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        ListPenghuni.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ListPenghuni.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListPenghuni.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        ScrollPane.setViewportView(ListPenghuni);

        PanelHapusDataPenghuni.add(ScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 218, 230, 110));

        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHapusMouseReleased(evt);
            }
        });
        PanelHapusDataPenghuni.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 367, 120, 50));

        LabelInfoHapus.setForeground(new java.awt.Color(212, 14, 14));
        LabelInfoHapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelHapusDataPenghuni.add(LabelInfoHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 414, 290, 20));

        btnBack2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBack2MouseReleased(evt);
            }
        });
        PanelHapusDataPenghuni.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 20, 20));

        BG5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xhapus data penghuni.JPG"))); // NOI18N
        PanelHapusDataPenghuni.add(BG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelHapusDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelCekDataPenghuni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TabelPenghuni.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TabelPenghuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPane1.setViewportView(TabelPenghuni);

        PanelCekDataPenghuni.add(ScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 215, 230, 183));

        btnBack3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBack3MouseReleased(evt);
            }
        });
        PanelCekDataPenghuni.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 20, 20));

        BG6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xcek data penghuni.JPG"))); // NOI18N
        PanelCekDataPenghuni.add(BG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelCekDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelKelolaDataPenghuni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInputDataPenghuni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInputDataPenghuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInputDataPenghuniMouseReleased(evt);
            }
        });
        PanelKelolaDataPenghuni.add(btnInputDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 103, 245, 70));

        btnHapusDataPenghuni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapusDataPenghuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHapusDataPenghuniMouseReleased(evt);
            }
        });
        PanelKelolaDataPenghuni.add(btnHapusDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 187, 242, 70));

        btnCekDataPenghuni.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCekDataPenghuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCekDataPenghuniMouseReleased(evt);
            }
        });
        PanelKelolaDataPenghuni.add(btnCekDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 272, 242, 70));

        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKembaliMouseReleased(evt);
            }
        });
        PanelKelolaDataPenghuni.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 372, 143, 47));

        BG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xkelola data penghuni 2.JPG"))); // NOI18N
        PanelKelolaDataPenghuni.add(BG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelKelolaDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelKelolaPembayaran.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStatusPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStatusPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStatusPembayaranMouseReleased(evt);
            }
        });
        PanelKelolaPembayaran.add(btnStatusPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 149, 272, 71));

        btnKonfirmasiPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKonfirmasiPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKonfirmasiPembayaranMouseReleased(evt);
            }
        });
        PanelKelolaPembayaran.add(btnKonfirmasiPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 250, 276, 70));

        btnKembaliPembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembaliPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKembaliPembayaranMouseReleased(evt);
            }
        });
        PanelKelolaPembayaran.add(btnKembaliPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 375, 145, 47));

        BG7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xkelola pembayaran.JPG"))); // NOI18N
        PanelKelolaPembayaran.add(BG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelKelolaPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelKirimPesan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKirim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKirimMouseReleased(evt);
            }
        });
        PanelKirimPesan.add(btnKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 363, 120, 50));

        ScrollPesan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ScrollPesan.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPesan.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        PesanArea.setColumns(20);
        PesanArea.setRows(5);
        PesanArea.setMaximumSize(new java.awt.Dimension(90134, 95777));
        PesanArea.setPreferredSize(new java.awt.Dimension(134, 95));
        ScrollPesan.setViewportView(PesanArea);

        PanelKirimPesan.add(ScrollPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 235, 134, 95));

        btnBack4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBack4MouseReleased(evt);
            }
        });
        PanelKirimPesan.add(btnBack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 20, 20));

        BG8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xkirim pesan.JPG"))); // NOI18N
        PanelKirimPesan.add(BG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelKirimPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelHalamanUtama.setPreferredSize(new java.awt.Dimension(350, 480));
        PanelHalamanUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKelolaDataHU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaDataHU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKelolaDataHUMouseReleased(evt);
            }
        });
        PanelHalamanUtama.add(btnKelolaDataHU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 241, 65));

        btnKelolaPembarayan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelolaPembarayan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKelolaPembarayanMouseReleased(evt);
            }
        });
        PanelHalamanUtama.add(btnKelolaPembarayan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 202, 241, 65));

        btnKirimPesan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKirimPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKirimPesanMouseReleased(evt);
            }
        });
        PanelHalamanUtama.add(btnKirimPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 282, 241, 65));

        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKeluarMouseReleased(evt);
            }
        });
        PanelHalamanUtama.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 359, 241, 65));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xhalaman utama.JPG"))); // NOI18N
        PanelHalamanUtama.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelHalamanUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelInputDataPenghuni.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfNamaPenghuni.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfNamaPenghuni.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelInputDataPenghuni.add(tfNamaPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 172, 190, 38));

        tfNoKamar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfNoKamar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelInputDataPenghuni.add(tfNoKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 224, 73, 38));

        tfNoHP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfNoHP.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelInputDataPenghuni.add(tfNoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 275, 190, 38));

        tfAsalPenghuni.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        tfAsalPenghuni.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        PanelInputDataPenghuni.add(tfAsalPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 326, 190, 38));

        btnInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnInputMouseReleased(evt);
            }
        });
        PanelInputDataPenghuni.add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 403, 120, 50));

        LabelSalahInputData.setForeground(new java.awt.Color(212, 14, 14));
        LabelSalahInputData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PanelInputDataPenghuni.add(LabelSalahInputData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 290, 20));

        BG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rpl/xinput data penghuni.JPG"))); // NOI18N
        PanelInputDataPenghuni.add(BG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBack1MouseReleased(evt);
            }
        });
        PanelInputDataPenghuni.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 20, 20));

        getContentPane().add(PanelInputDataPenghuni, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseReleased
        System.exit(0); // untuk keluar
    }//GEN-LAST:event_btnKeluarMouseReleased

    private void btnKembaliMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseReleased
        //Kembali ke halaman utama
        setView(false, true, false, false, false, false, false, false, false, false);
    }//GEN-LAST:event_btnKembaliMouseReleased

    private void btnMasukMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukMouseReleased
        //Kalau Password dengan Usernamenya sesuai langsung ke menu utama
        if (tfUsername.getText().equals("bapakkos") && tfPassword.getText().equals("kostan")) {
            setView(false, true, false, false, false, false, false, false, false, false);
        } else {
            LabelSalahLogin.setText("Nama pengguna atau password salah");
            tfUsername.setText("");
            tfPassword.setText("");
        }
    }//GEN-LAST:event_btnMasukMouseReleased

    private void btnInputMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputMouseReleased
        //Untuk menginput data
        Penghuni x = model.cariPenghuni(tfNamaPenghuni.getText());
        if (x == null) {
            Penghuni p = new Penghuni(tfNamaPenghuni.getText(), new Kamar(tfNoKamar.getText()), tfNoHP.getText(), tfAsalPenghuni.getText());
            System.out.println(p.getNama());
            model.addPenghuni(p);
        } else {
            //pemberitahuan kalau penghuni udah terdaftar
            LabelSalahInputData.setText("Penghuni sudah terdaftar");
            tfNamaPenghuni.setText("");
            tfNoKamar.setText("");
            tfNoHP.setText("");
            tfNoKamar.setText("");
        }
    }//GEN-LAST:event_btnInputMouseReleased

    private void btnHapusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseReleased
        Penghuni x = model.cariPenghuni((String) ListPenghuni.getSelectedValue());
        System.out.println((String)ListPenghuni.getSelectedValue());
        if (x == null || x.equals("")) 
            
            //pemberitahuan kalau tidak ada penghuni dengan nama tsbt.
        } else {
            model.hapusPenghuni(x);
        }
        System.out.println(x.getNama());
    }//GEN-LAST:event_btnHapusMouseReleased

    private void btnKembaliPembayaranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliPembayaranMouseReleased
        //Kembali ke halaman utama
        setView(false, true, false, false, false, false, false, false, false, false);
    }//GEN-LAST:event_btnKembaliPembayaranMouseReleased

    private void btnKelolaDataHUMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelolaDataHUMouseReleased
        //Ke panel kelola data
        setView(false, false, true, false, false, false, false, false, false, false);
    }//GEN-LAST:event_btnKelolaDataHUMouseReleased

    private void btnKelolaPembarayanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelolaPembarayanMouseReleased
        //ke panel kelola pembayaran
        setView(false, false, false, true, false, false, false, false, false, false);
    }//GEN-LAST:event_btnKelolaPembarayanMouseReleased

    private void btnInputDataPenghuniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputDataPenghuniMouseReleased
        //ke panel Input data
        setView(false, false, false, false, true, false, false, false, false, false);
    }//GEN-LAST:event_btnInputDataPenghuniMouseReleased

    private void btnHapusDataPenghuniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusDataPenghuniMouseReleased
        //ke panel hapus data
        String[] list = model.queryviewhapus();
        DefaultListModel dlm =  new DefaultListModel();
        for (int i = 0; i < list.length; i++) {
            dlm.addElement(list[i]);
            i++;
        }
        ListPenghuni.setModel(dlm);
        setView(false, false, false, false, false, true, false, false, false, false);
    }//GEN-LAST:event_btnHapusDataPenghuniMouseReleased

    private void btnCekDataPenghuniMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekDataPenghuniMouseReleased
        //ke panel cek data
        String[][] data = model.queryview();
        String[] columnNames = {"id penghuni", "nama penghuni", "asal penghuni", "no hp penghuni", "no kamar", "tanggal masuk"};
        TabelPenghuni.setModel(new DefaultTableModel(data, columnNames));
        setView(false, false, false, false, false, false, true, false, false, false);
    }//GEN-LAST:event_btnCekDataPenghuniMouseReleased

    private void btnKirimMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseReleased
        // kalau kirim pesan
    }//GEN-LAST:event_btnKirimMouseReleased

    private void btnKirimPesanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimPesanMouseReleased
        //ke panel kirim pesan
        setView(false, false, false, false, false, false, false, true, false, false);
    }//GEN-LAST:event_btnKirimPesanMouseReleased
    private int yMouse;
    private int xMouse;
    private void MoveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveMouseDragged
        //move frame
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_MoveMouseDragged

    private void MoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoveMousePressed
        //move frame
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_MoveMousePressed

    private void btnBack1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack1MouseReleased
        //kembali ke panel kelola data
        setView(false, false, true, false, false, false, false, false, false, false);
    }//GEN-LAST:event_btnBack1MouseReleased

    private void btnBack3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack3MouseReleased
        //kembali ke panel kelola data        
        setView(false, false, true, false, false, false, false, false, false, false);
    }//GEN-LAST:event_btnBack3MouseReleased

    private void btnBack2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack2MouseReleased
        //kembali ke panel kelola data
        setView(false, false, true, false, false, false, false, false, false, false);
    }//GEN-LAST:event_btnBack2MouseReleased

    private void btnBack4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack4MouseReleased
        //kembali ke panel menu utama
        setView(false, true, false, false, false, false, false, false, false, false);
    }//GEN-LAST:event_btnBack4MouseReleased

    private void btnKonfirmasiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKonfirmasiMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKonfirmasiMouseReleased

    private void btnBack5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack5MouseReleased
        //kembali ke panel pembayaran
        setView(false, false, false, true, false, false, false, false, false, false);
    }//GEN-LAST:event_btnBack5MouseReleased

    private void btnBack6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBack6MouseReleased
        //kembali ke panel pembayaran
        setView(false, false, false, true, false, false, false, false, false, false);
    }//GEN-LAST:event_btnBack6MouseReleased

    private void btnStatusPembayaranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatusPembayaranMouseReleased
        //ke panel status transaksi
        setView(false, false, false, false, false, false, false, false, false, true);
    }//GEN-LAST:event_btnStatusPembayaranMouseReleased

    private void btnKonfirmasiPembayaranMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKonfirmasiPembayaranMouseReleased
        //ke panel konfirmasi pembayaran
        setView(false, false, false, false, false, false, false, false, true, false);
    }//GEN-LAST:event_btnKonfirmasiPembayaranMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    public JLabel getBtnHapus() {
        return btnHapus;
    }

    public JLabel getBtnHapusDataPenghuni() {
        return btnHapusDataPenghuni;
    }

    public JLabel getBtnInput() {
        return btnInput;
    }

    public JLabel getBtnInputDataPenghuni() {
        return btnInputDataPenghuni;
    }

    public JTextField getTfAsalPenghuni() {
        return tfAsalPenghuni;
    }

    public JTextField getTfNamaPenghuni() {
        return tfNamaPenghuni;
    }

    public JTextField getTfNoHP() {
        return tfNoHP;
    }

    public JTextField getTfNoKamar() {
        return tfNoKamar;
    }

    public JPasswordField getTfPassword() {
        return tfPassword;
    }

    public JTextField getTfUsername() {
        return tfUsername;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel BG10;
    private javax.swing.JLabel BG2;
    private javax.swing.JLabel BG3;
    private javax.swing.JLabel BG4;
    private javax.swing.JLabel BG5;
    private javax.swing.JLabel BG6;
    private javax.swing.JLabel BG7;
    private javax.swing.JLabel BG8;
    private javax.swing.JLabel BG9;
    private javax.swing.JLabel LabelInfoHapus;
    private javax.swing.JLabel LabelSalahInputData;
    private javax.swing.JLabel LabelSalahLogin;
    private javax.swing.JList ListPenghuni;
    private javax.swing.JLabel Move;
    private javax.swing.JPanel PanelCekDataPenghuni;
    private javax.swing.JPanel PanelHalamanUtama;
    private javax.swing.JPanel PanelHapusDataPenghuni;
    private javax.swing.JPanel PanelInputDataPenghuni;
    private javax.swing.JPanel PanelKelolaDataPenghuni;
    private javax.swing.JPanel PanelKelolaPembayaran;
    private javax.swing.JPanel PanelKirimPesan;
    private javax.swing.JPanel PanelKonfirmasiPembayaran;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel PanelStatusTransaksi;
    private javax.swing.JTextArea PesanArea;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPesan;
    private javax.swing.JTable TabelPenghuni;
    private javax.swing.JLabel btnBack1;
    private javax.swing.JLabel btnBack2;
    private javax.swing.JLabel btnBack3;
    private javax.swing.JLabel btnBack4;
    private javax.swing.JLabel btnBack5;
    private javax.swing.JLabel btnBack6;
    private javax.swing.JLabel btnCekDataPenghuni;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnHapusDataPenghuni;
    private javax.swing.JLabel btnInput;
    private javax.swing.JLabel btnInputDataPenghuni;
    private javax.swing.JLabel btnKelolaDataHU;
    private javax.swing.JLabel btnKelolaPembarayan;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnKembali;
    private javax.swing.JLabel btnKembaliPembayaran;
    private javax.swing.JLabel btnKirim;
    private javax.swing.JLabel btnKirimPesan;
    private javax.swing.JLabel btnKonfirmasi;
    private javax.swing.JLabel btnKonfirmasiPembayaran;
    private javax.swing.JLabel btnMasuk;
    private javax.swing.JLabel btnStatusPembayaran;
    private javax.swing.JTextField tfAsalPenghuni;
    private javax.swing.JTextField tfNamaPenghuni;
    private javax.swing.JTextField tfNoHP;
    private javax.swing.JTextField tfNoKamar;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
